#!/bin/bash

nparams="$#"
# Heap space memory for JVM
defaultMinMem=100
defaultMaxMem=300
if [ "$CROSSDICS_PATH" = "" ];
then
	CROSSDICS_PATH="/usr/local/apertium-dixtools"
fi

library="$CROSSDICS_PATH/dist/apertium-dixtools.jar"
java_options="-Xms${defaultMinMem}m -Xmx${defaultMaxMem}m -jar ${library} cross"

if [ $nparams -ge 3 ]; then
 if [ ! -d "dix" ]; then
   mkdir dix
 fi
  java ${java_options} cross2 $1 $2 $3
else
  echo "Usage: apertium-crossdics -f <ling-resources.xml> <sl-tl>";
  echo "";
  echo "More information in http://wiki.apertium.org/wiki/Apertium-dixtools";
  echo "";
fi



