#!/bin/bash

nparams="$#"
mainClass="ProcessDics"
# Minimum and maximum memory for JVM
defaultMinMem=32
defaultMaxMem=300
if [ "$CROSSDICS_PATH" = "" ];
then
	CROSSDICS_PATH="/usr/local/apertium-crossdics"
fi

library="$CROSSDICS_PATH/dist/crossdics.jar"
java_options="-Xms${defaultMinMem}m -Xmx${defaultMaxMem}m -jar ${library} cross"

if [ $nparams -ge 3 ]; then
 if [ ! -d "dix" ]; then
   mkdir dix
 fi
  java ${java_options} cross2 $1 $2 $3
else
  #echo "Usage: apertium-crossdics <-f|-url> <ling-resources.xml> <sl-tl>";
  echo "Usage: apertium-crossdics -f <ling-resources.xml> <sl-tl>";
  echo "";
  echo "More information in http://xixona.dlsi.ua.es/wiki/index.php/Crossdics";
  echo "";
fi



