#!/bin/bash

# Heap space memory for JVM
defaultMinMem=500
defaultMaxMem=800
if [ "$CROSSDICS_PATH" = "" ];
then
	CROSSDICS_PATH="/usr/local/apertium-dixtools"
fi
library="$CROSSDICS_PATH/dist/apertium-dixtools.jar"
java_options="-Xms${defaultMinMem}m -Xmx${defaultMaxMem}m -jar ${library}"


#
#	cross-param
#
function cross-param() {
   if [ $nparams -ge 7 ] && [ $nparams -le 9  ]; then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
#   crossmodel="$CROSSDICS_PATH/schemas/cross-model.xml"
#	read i
#	   if [ $nparams -ge 8 ]
#   	then
#	   	crossmodel=$8
#   	fi
#	   echo "cross model: $crossmodel"
#   	if [ ! -d "dix" ]
#     	then
#             mkdir dix
#        fi
#               	   
#   	java ${java_options} $task -bilAB $3 $4 -bilBC $5 $6 -monA $2 -monC $7 -cross-model $crossmodel $9
   else
#	show_help2();
   	echo "Usage: dictools cross <monA> <-r|-n> <bilAB> <-r|-n> <bilBC> <monC> crossmodel";
   	echo "";
   	echo "More information in http://wiki.apertium.org/wiki/Crossdics";
   	echo "";
   fi
}

#
#	cross
#
function cross() {
   if [ $nparams -ge 4 ]; then
   	if [ ! -d "dix" ]
     	then
             mkdir dix
        fi
#   	java ${java_options} $task $2 $3 $4
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
   else
   	echo "Usage: dictools cross -f <ling-resources.xml> <sl-tl>";
   	echo "";
   	echo "More information in http://wiki.apertium.org/wiki/Crossdics";
   	echo "";
   fi
}

#
#  format
#
function format() {
   if [ $nparams -ge 4 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
#      echo "Reading '$3'..."
#   	java ${java_options} $task $2 $3 $4 2> format.err
#      echo "Formatted dictonary: $4"
#      echo "Log file in 'format.err'"
   else
      echo "Usage: dictools format <-mon|-bil> <dic> <out>"
      echo "";
      echo "More information: http://wiki.apertium.org/wiki/Format_dictionaries";
      echo "";
   fi
}

#
#  merge-morph
#
function merge-morph() {
   if [ $nparams -ge 4 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
#      java ${java_options} $task -monA1 $2 -monA2 $3 -out $4 $5
      echo "Merged dictionary: $4"
   else
      echo "Usage: dictools merge-morph <monA1> <monA2> <merged>"
      echo "";
      echo "More information: http://wiki.apertium.org/wiki/Merge_dictionaries";
      echo "";
   fi
}

#
#  merge-bil
#
function merge-bil() {
   if [ $nparams -eq 6 ]; then
	   echo "Bilingual 1: $3"
   	echo "mode: $2"
	   echo "Bilingual 2: $5"
   	echo "mode: $4"
      java ${java_options} $task -bilAB1 $2 $3 -bilAB2 $4 $5 -out $6
      echo "Merged: $6"
   else
   	echo "Usage: dictools merge-bil <-n|-r> <bilAB1> <-n|-r> <bilAB2> <merged>";
   	echo "";
   fi
}

#
#  reverse-bil
#
function reverse-bil() {
   if [ $nparams -ge 3 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
#      echo "Reading '$2'..."
#   	java ${java_options} reverse $2 $3 2> reverse-bil.err      
   else
      echo "Usage: dictools reverse-bil <dic> <out>";
      echo "";
      echo "More information: http://wiki.apertium.org/wiki/Reverse_a_dictionary";
      echo "";
   fi
}

#
#  sort
#
function sort() {
   if [ $nparams -ge 4 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
#      echo "Reading '$3' ($2)"
#      java ${java_options} $task $2 $3 $4
#      echo "Sorted: $4"
   else
      echo "Usage: dictools sort <-bil|-mon> <dic.dix> <out.dix>";
      echo "";
      echo "More information: http://wiki.apertium.org/wiki/Sort_a_dictionary";
      echo "";
   fi
}

#
#  process-xincludes
#
function process-xincludes() {
   if [ $nparams -ge 3 ]
   then
      java ${java_options} gather $2 $3 $4 $5 $6 $7 $8 $9
      echo "Dictionary: $3"
   else
      echo "Usage: dictools process-xincludes <dic> <out.dix>";
      echo "";
      #echo "More information: ";
      #echo "";
   fi
}

#
#  get-bil-omegawiki
#
function get-bil-omegawiki() {
   if [ $nparams -ge 4 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
      echo "Dictionary: $4"
   else
      echo "Usage: dictools get-bil-omegawiki <source-lang> <target-lang> <dic-out>"
      echo "";
      echo "More information: http://wiki.apertium.org/wiki/Getting_bilingual_dictionaries_from_OmegaWiki";
      echo "";
   fi
}

#
#  format-1line
#
function format-1line() {
   if [ $nparams -ge 3 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
   else
      echo "Usage: dictools format-1line [alignP alignR] <input-dic> <output-dic>"
      echo "       where alignP / alignR: column to align <p> and <r> entries. 0 = no indent."
      echo "";
      echo "Example: ' format-1line old.dix new.dix '   will give indent a la"
      echo '<e><p><l>dum<s n="cnjadv"/></l><r>whereas<s n="cnjadv"/></r></p></e>'
      echo "";
      echo "Example: ' format-1line 10 50 old.dix new.dix '   will give indent a la"
      echo '<e>       <p><l>dum<s n="cnjadv"/></l>            <r>whereas<s n="cnjadv"/></r></p></e>'
      echo "";
      echo "Example: ' format-1line 0 50 old.dix new.dix '   will give indent a la"
      echo '<e><p><l>dum<s n="cnjadv"/></l>                   <r>whereas<s n="cnjadv"/></r></p></e>'
      echo "";
      echo "Example: ' format-1line 10 0 old.dix new.dix '   will give indent a la"
      echo '<e>       <p><l>dum<s n="cnjadv"/></l><r>whereas<s n="cnjadv"/></r></p></e>'
      echo "";
      echo "More information: http://wiki.apertium.org/wiki/Format_dictionaries";
      echo "";
   fi
}

#
#  read-dic
#
function dic-reader() {
   if [ $nparams -ge 3 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
   else
      echo "Usage: dictools dic-reader <action> <dic>"
      echo "where <action> can be:"
      echo "   list-paradigms:   list of paradigms";
      echo "   list-lemmas:      list of lemmas";
      echo "   list-definitions: list of <sdef> elemenst";
      echo "   list-pairs:       list of pairs (for bilingual dictionaries";
      echo "";
      echo "More information: http://wiki.apertium.org/wiki/Dictionary_reader";
      echo "";
   fi
}

#
#  equiv-paradigms
#
function equiv-paradigms() {
   if [ $nparams -ge 2 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
   else
      echo "Usage: dictools equiv-paradigms <dic> <out>"
      echo "";
      echo "More information: http://wiki.apertium.org/wiki/Equivalent_paradigms";
      echo "";
   fi
}

#
#  dix2trie
#
function dix2trie() {
   if [ $nparams -ge 3 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
   else
      echo "Usage: dictools dic2trie <dic> <lr|rl> [<out>]"
      echo "";
   fi
}

#
#  dix2cc
#
function dix2cc() {
   if [ $nparams -ge 3 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
   else
      echo "Usage: apertium-dixtools dix2cc <dix> <cc>"
      echo "";
   fi
}

#
#  dix2tiny
#
function dix2tiny() {
   if [ $nparams -ge 5 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6
   else
      echo ""
      echo "Usage: apertium-dixtools dix2tiny <dix> <lang-pair> <lang-pair-text> <platform> [<filter>]"
      echo "Options:"
      echo "  platforms: j2me, palm, all"
      echo "Example:"
      echo "  apertium-dixtools dix2tiny apertium-es-ca.es-ca.dix es-ca Spanish-Catalan j2me [filter-es-ca.xml]"
      echo ""
   fi
}

#
#  apertiumizer
#
function apertiumize() {
   if [ $nparams -ge 2 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
   else
      echo "Usage: dictools apertiumize <txt> <out>"
      echo "";
   fi
}

#
#  filter
#
function filter() {
   if [ $nparams -ge 2 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
   else
      echo "Usage: apertium-dixtools filter <dicA> <dicB>"
      echo "";
   fi
}



#
#  convert-mf
#
function convert-mf() {
   if [ $nparams -ge 3 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
   else
      echo "Usage: dictools convert-mf <morph> <bil> <out>"
      echo "";
   fi
}

#
#  add-same-gender
#
function add-same-gender() {
   if [ $nparams -ge 3 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
   else
      echo "Usage: dictools add-same-gender <morph> <bil> <out>"
      echo "";
   fi
}

#
#  prepare-dic
#
function prepare-dic() {
   if [ $nparams -ge 2 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
   else
      echo "Usage: dictools prepare-dic <bil> <missing-entries>>"
      echo "";
      #echo "More information: http://wiki.apertium.org/wiki/Equivalent_paradigms";
      #echo "";
   fi
}

#
#  complete-translation
#
function complete-translation() {
   if [ $nparams -ge 3 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
   else
      echo "Usage: dictools complete-translation <bil> <src-dot> <trans-dot>"
      echo "";
   fi
}

#
#  misc
#
function misc() {
   if [ $nparams -ge 4 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
   else
      echo "Usage: dictools misc <dic1> <dic2> <dic3> <dic4>"
      echo "";
   fi
}

#
#  misc
#
function cat() {
   if [ $nparams -ge 2 ]
   then
   	java ${java_options} $task $2 $3 $4 $5 $6 $7 $8 $9
   else
      echo "Usage: dictools cat <input-dic> <output-dic>"
      echo "";
   fi
}

#
#  show_help
#
function show_help() {
   echo ""
   echo "Usage: apertium-dixtools [task] [generic options] task parameters ..."
   echo "  Tasks:"
   echo "    cat:                print a dictionary (with format according to generic options)"
   echo "    cross:              crosses a set of dictionaries"
   echo "    dic-reader:         reads elements from a dictionary"
   echo "    dix2tiny:           generates linguistic data for mobile platforms (j2me, palm)"
   echo "    dix2trie:           creates a Trie from an existing bilingual dictionary"
   echo "    equiv-paradigms:    finds equivalent paradigms and updates references"
   echo "    format:             formats a dictionary"   
   echo "    format-1line:       formats a dictionary (1 element per line)"
   #echo "    merge-bil:          merges two bilingual dictionaries"
   echo "    merge-morph:        merges two morphological dictionaries"
   #echo "    process-xincludes:  processes and expands all xincludes in the dictionary"
   echo "    reverse-bil:        reverses a bilingual dictionary"
   echo "    sort:               sorts (and groups by category) a dictionary"
   echo ""
   echo "  Generic options:"
   echo "    -debug                        prints (possibly) some debugging information"
   echo "    -align [alignP alignR]        aligns output dix elements (default alignP=10 alignR=55)"
   echo "    -alignpardef [alignP alignR]  aligns paradigm elements"
   echo "    -stripEmptyLines    removes empty lines originating from original file"
   echo "    -noProcComments    don't add comments telling which processing was done"
   echo ""
   echo "More info: http://wiki.apertium.org/wiki/Apertium-dixtools"
   echo ""
   exit 127
}


function show_help2() {
   	java ${java_options} help $0 $1 $2 $3 $4 $5 $6 $7 $8 $9
}



task=$1
nparams="$#"
params="$@"
if [ "$#" == 0 ]; then
   show_help
else
   $task $params
fi
