#!/bin/bash

echo ""
echo "dictools is now called apertium-dictools"
echo ""
echo "Usage: apertium-dictools ..."
echo ""
echo "More information in http://xixona.dlsi.ua.es/wiki/index.php/Crossdics";
echo "";
            