#!/bin/bash

mainClass="ProcessDics"
# Minimum and maximum memory for JVM
defaultMinMem=32
defaultMaxMem=300
library='lib/cross-dics.jar'
java_options="-Xms${defaultMinMem}m -Xmx${defaultMaxMem}m -cp ${library} $mainClass"
#java_options="-Xms${defaultMinMem}m -Xmx${defaultMaxMem}m -cp $CLASSPATH $mainClass"
#echo $java_options

#
#	cross
#
function cross() {
   crossmodel="schemas/cross-model-test.xml"
   if [ $nparams -ge 7 ] && [ $nparams -le 9  ]; then
	   if [ $nparams -ge 8 ]
   	then
	   	crossmodel=$8
   	fi
	   echo "cross model: $crossmodel"
   	java ${java_options} $task -bilAB $3 $4 -bilBC $5 $6 -monA $2 -monC $7 -cross-model $crossmodel $9 2> $task.err
   else
   	echo "Usage: dictools cross <monA> <-r|-n> <bilAB> <-r|-n> <bilBC> <monC> crossmodel"
   	echo "More information in http://xixona.dlsi.ua.es/wiki/index.php/Crossdics";
   fi
}

#
#  format
#
function format() {
   if [ $nparams == 4 ]
   then
      echo "Reading '$3'..."
   	java ${java_options} $task $2 $3 $4 2> format.err
      echo "Formatted dictonary: $4"
      echo "Log file in 'format.err'"
   else
      echo "Usage: dictools format <-mon|-bil> <dic> <out>"
   fi
}

#
#  merge-morph
#
function merge-morph() {
   if [ $nparams -ge 4 ]
   then
      echo "Morphological 1: $2"
      echo "Morphological 2: $3"
      java ${java_options} $task -monA1 $2 -monA2 $3 -out $4 $5
      echo "Merged dictionary: $4"
   else
      echo "Usage: dictools merge-morph <monA1> <monA2> <merged>"
   fi
}

#
#  merge-bil
#
function merge-bil() {
   if [ $nparams -eq 6 ]; then
	   echo "Bilingual 1: $3"
   	echo "mode: $2"
	   echo "Bilingual 2: $5"
   	echo "mode: $4"
      java ${java_options} $task -bilAB1 $2 $3 -bilAB2 $4 $5 -out $6
      echo "Merged: $6"
   else
   	echo "Usage: dictools merge-bil <-n|-r> <bilAB1> <-n|-r> <bilAB2> <merged>"
   fi
}

#
#  reverse-bil
#
function reverse-bil() {
   if [ $nparams == 3 ]
   then
      echo "Reading '$2'..."
   	java ${java_options} reverse $2 $3 2> reverse-bil.err      
   else
      echo "Usage: dictools reverse-bil <dic> <out>"
   fi
}

#
#  sort
#
function sort() {
   if [ $nparams == 5 ]
   then
      echo "Reading '$4' ($2)"
      java ${java_options} $task $2 $3 $4 $5
      echo "Sorted: $5"
   else
      echo "Usage: dictools sort <-bil|-mon> <-xinclude|-same-file> <dic.dix> <out.dix>"
   fi
}

#
#  process-xincludes
#
function process-xincludes() {
   if [ $nparams == 3 ]
   then
      java ${java_options} gather $2 $3
      echo "Dictionary: $3"
   else
      echo "Usage: dictools process-xincludes <dic> <out.dix>"
   fi
}

#
#  get-bil-omegawiki
#
function get-bil-omegawiki() {
   if [ $nparams == 4 ]
   then
      java ${java_options} $task $2 $3 $4
      echo "Dictionary: $4"
   else
      echo "Usage: dictools get-bil-omegawiki <source-lang> <target-lang> <dic-out>"
   fi
}

#
#  format-1line
#
function format-1line() {
   if [ $nparams == 3 ]
   then
      java ${java_options} $task $2 $3
      echo "Dictionary: $3"
   else
      echo "Usage: dictools format-1line <dic> <dic-out>"
   fi
}


#
#  show_help
#
function show_help() {
   echo "Usage: dictools [task] ..."
   echo "  Tasks:"
   echo "    cross:    crosses a set of dictionaries."
   echo "    format:       formats a dictionary."   
   echo "    merge-bil:    merges two bilingual dictionaries."
   echo "    merge-morph:  merges two morphological dictionaries."
   echo "    process-xincludes: processes all xincludes in the dictionary and expands them."
   echo "    reverse-bil:  reverses a bilingual dictionary."
   echo "    sort:         sorts (and groups by category) a dictionary."
   exit 127
}

task=$1
nparams="$#"
params="$@"
if [ "$#" == 0 ]; then
   show_help
else
   $task $params
fi

